flowchart TD
    docs__examples["docs.examples<br/>1 funcs"]
    fixos__agent["fixos.agent<br/>75 funcs"]
    fixos__anonymizer["fixos.anonymizer<br/>2 funcs"]
    fixos__cli["fixos.cli<br/>81 funcs"]
    fixos__config["fixos.config<br/>7 funcs"]
    fixos__llm_shell["fixos.llm_shell<br/>4 funcs"]
    fixos__orchestrator["fixos.orchestrator<br/>41 funcs"]
    fixos__platform_utils["fixos.platform_utils<br/>10 funcs"]
    fixos__plugins["fixos.plugins<br/>44 funcs"]
    fixos__system_checks["fixos.system_checks<br/>8 funcs"]
    fixos__utils["fixos.utils<br/>33 funcs"]
    project__map["project.map<br/>208 funcs"]
    fixos__plugins ==>|32| fixos__platform_utils
    fixos__agent ==>|10| fixos__utils
    fixos__agent ==>|9| fixos__platform_utils
    fixos__agent ==>|8| fixos__anonymizer
    fixos__agent ==>|6| project__map
    fixos__orchestrator ==>|4| fixos__anonymizer
    fixos__orchestrator ==>|4| project__map
    fixos__cli -->|2| fixos__config
    fixos__cli -->|2| fixos__system_checks
    fixos__llm_shell -->|1| fixos__anonymizer
    fixos__cli -->|1| project__map
    fixos__cli -->|1| fixos__anonymizer
    fixos__cli -->|1| docs__examples
    fixos__cli -->|1| fixos__agent
